---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitea-webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: gitea-webhook-trigger
      bindings:
        - ref: gitea-triggerbinding
      template:
        ref: gitea-trigger-template