apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-push
  annotations:
    description: build and push docker images
spec:
  workspaces:
  - name: work
    mountPath: /work
  params:
  - name: build-path
    type: string
    description: path to dockerfile
    default: "."
  - name: image
    type: string
    description: path to dockerfile
    default: "."
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v0.17.1
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/work/source/$(params.build-path)/Dockerfile
        - --destination=$(params.image)
        - --context=/work/source/$(params.build-path)