apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: parse-config
  namespace: tekton-pipelines
  annotations:
    description: Parse tekton config
spec:
  workspaces:
  - name: work
    mountPath: /work
  results:
    - name: image
      description: Image to be built
    - name: tag
      description: Tag of image
    - name: build_path
      description: Path in repo of Dockerfile
  steps:
    - name: parse-config
      image: harbor.atoy.dev/public/yq:1.1
      script: |
        #!/usr/bin/env ash

        if [[ ! -f /work/source/.tekton.yaml ]]; then
          echo "ERROR: Missing '.tekton.yaml' in repository."
          exit 1
        fi

        cat /work/source/.tekton.yaml | yq -r '.docker.image.name' | tr -d '\n' | tee $(results.image.path)
        cat /work/source/.tekton.yaml | yq -r '.docker.image.tag' | tr -d '\n' | tee $(results.tag.path)
        cat /work/source/.tekton.yaml | yq -r '.docker.build_path' | tr -d '\n' | tee $(results.build_path.path)  


