apiVersion: v1
kind: Secret
metadata:
  name: harbor-creds
  annotations:
    tekton.dev/docker-0: https://harbor.atoy.dev
type: kubernetes.io/basic-auth
stringData:
  username: adam.toy
  password: CnElZW7cpT1fxhHMG1fHi1ASBEnrYZY2