apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/docker-0: https://harbor.atoy.dev
    name: harbor-creds
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: secrets/data/tekton/harbor
      property: data.username
  - secretKey: password
    remoteRef:
      key: secrets/data/tekton/harbor
      property: data.password