apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-key
  annotations:
    tekton.dev/git-0: git-ssh.atoy.lol
    tekton.dev/git-1: git.atoy.lol
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-key
    creationPolicy: Owner
  data:
  - secretKey: ssh-privatekey
    remoteRef:
      key: secrets/data/tekton/gitea
      property: data.ssh-privatekey
  - secretKey: known_hosts
    remoteRef:
      key: secrets/data/tekton/gitea
      property: data.known_hosts